{
 "title": "Gird Search Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "language", "query": "scala,cpp,go,julia,elixir" },
   { "name": "window", "query": "1min,2min,5min,10min" }
  ]
 },
 "panels": [
  {
   "title": "Per node throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(stats.*.results_produced, 'avg'), '$window'), 'mean')"
    },
    {
     "target": "alias(movingAverage(aggregate(stats.*.results_produced, 'max'), '$window'), 'max')"
    },
    {
     "target": "alias(movingAverage(aggregate(stats.*.results_produced, 'min'), '$window'), 'min')"
    }
   ]
  },
  {
   "title": "Measured Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "groupByNodes(stats.gauges.cadvisor.gs_{$language}_worker.*.*.memory_usage, 'count')"
    }
   ]
  },
  {
   "title": "Combined throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(stats.*.results_produced, 'sum'), '$window'), 'throughput')"
    }
   ]
  },
  {
   "title": "Completion time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.manager.completion_time"
    }
   ]
  },
  {
   "title": "Coefficient of variation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$F/$E", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage (Workers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.gs_{$language}_worker.*.*.memory_usage, 4, 'sum'), 'average'), '$window'), 'mean')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.gs_{$language}_worker.*.*.memory_usage, 4, 'sum'), 'max'), '$window'), 'max')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.gs_{$language}_worker.*.*.memory_usage, 4, 'sum'), 'min'), '$window'), 'min')"
    }
   ]
  },
  {
   "title": "CPU Usage (Workers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Network Usage (Workers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(aggregate(filterSeries(groupByNode(stats.gauges.cadvisor.gs_${language}_worker.*.*.rx_bytes, 4, 'sum'), 'avg', '>', 0), 'avg'), 'received')"
    },
    {
     "target": "alias(aggregate(filterSeries(groupByNode(stats.gauges.cadvisor.gs_${language}_worker.*.*.tx_bytes, 4, 'sum'), 'avg', '>', 0), 'avg'), 'transmitted')"
    }
   ]
  }
 ]
}