version: "3.7"

x-worker-template: &worker-template
  image: elixir:alpine
  working_dir: /app
  volumes:
    - ../distributed_pipeline:/app
    - ../scripts:/app/scripts
  command: sh -c "/app/scripts/setup.sh ; iex --sname worker --cookie ${SECRET} -S mix"
  environment:
    - REPLICA={{.Task.Slot}}
    
services:
  worker:
    <<: *worker-template
    hostname: worker_{{.Task.Slot}}
    deploy:
      replicas: ${WORKER_REPLICAS}

  manager:
    image: elixir:alpine
    hostname: manager
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ../distributed_pipeline:/app
      - ../scripts:/app/scripts
    command: sh -c "/app/scripts/setup.sh ; tail -f /dev/null"
    environment:
      - WORKER_REPLICAS=${WORKER_REPLICAS}
